ContactListManagement.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ContactListManagement.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ContactListManagement.Web/Pages/Index.cshtml.cs
using ContactListManagement.Core.Entities;
using ContactListManagement.Core.Interfaces;
using ContactListManagement.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ContactListManagement.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IContactListRepositoryAsync _contactList;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IRazorRenderService _renderService;
        private readonly ILogger<IndexModel> _logger;
        public IndexModel(ILogger<IndexModel> logger, IContactListRepositoryAsync contactList, IUnitOfWork unitOfWork, IRazorRenderService renderService)
        {
            _logger = logger;
            _contactList = contactList;
            _unitOfWork = unitOfWork;
            _renderService = renderService;
        }
        public IEnumerable<ContactList> ContactLists { get; set; }
        public void OnGet()
        {
        }
        public async Task<PartialViewResult> OnGetViewAllPartial()
        {
            ContactLists = await _contactList.GetAllAsync();
            return new PartialViewResult
            {
                ViewName = "_ViewAll",
                ViewData = new ViewDataDictionary<IEnumerable<ContactList>>(ViewData, ContactLists)
            };
        }
        public async Task<JsonResult> OnGetCreateOrEditAsync(int id = 0)
        {
            if (id == 0)
                return new JsonResult(new { isValid = true, html = await _renderService.ToStringAsync("_CreateOrEdit", new ContactList()) });
            else
            {
                var thisContactList = await _contactList.GetByIdAsync(id);
                return new JsonResult(new { isValid = true, html = await _renderService.ToStringAsync("_CreateOrEdit", thisContactList) });
            }
        }
        public async Task<JsonResult> OnPostCreateOrEditAsync(int id, ContactList contactList)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                {
                    await _contactList.AddAsync(contactList);
                    await _unitOfWork.Commit();
                }
                else
                {
                    await _contactList.UpdateAsync(contactList);
                    await _unitOfWork.Commit();
                }
                ContactLists = await _contactList.GetAllAsync();
                var html = await _renderService.ToStringAsync("_ViewAll", ContactLists);
                return new JsonResult(new { isValid = true, html = html });
            }
            else
            {
                var html = await _renderService.ToStringAsync("_CreateOrEdit", contactList);
                return new JsonResult(new { isValid = false, html = html });
            }
        }
        public async Task<JsonResult> OnPostDeleteAsync(int id)
        {
            var contactList = await _contactList.GetByIdAsync(id);
            await _contactList.DeleteAsync(contactList);
            await _unitOfWork.Commit();
            ContactLists = await _contactList.GetAllAsync();
            var html = await _renderService.ToStringAsync("_ViewAll", ContactLists);
            return new JsonResult(new { isValid = true, html = html });
        }
    }
}

ContactListManagement.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactListManagement.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ContactListManagement.Web/Pages/_CreateOrEdit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactListManagement.Web.Pages
{
    public class _CreateOrEditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ContactListManagement.Web/Pages/_ViewAll.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ContactListManagement.Web.Pages
{
    public class _ViewAllModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ContactListManagement.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="card">
    <div class="col-sm-12" style="padding:20px">
        <a onclick="jQueryModalGet('?handler=CreateOrEdit','Create Contact List')" class="btn bg-success">
            Add Contact
        </a>
    </div>
    <div id="viewAll" class="card-body table-responsive"></div>
</div>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $('#viewAll').load('?handler=ViewAllPartial');
        });
        $(function () {
            $('#reload').on('click', function () {
                $('#viewAll').load('?handler=ViewAllPartial');
            });
        });
    </script>
}
Footer
© 2022 GitHub, Inc.
Footer navigation

ContactListManagement.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactListManagement.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactListManagement.Web.styles.css" asp-append-version="true" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ContactListManagement.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false" id="form-modal">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ContactListManagement.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ContactListManagement.Web/Pages/_CreateOrEdit.cshtml
@using Core.Entities
@model ContactList
<form id="create-form" method="post" asp-page="Index" asp-route-id="@Model.Id" asp-page-handler="CreateOrEdit" onsubmit="return jQueryModalPost(this);">
    <div class="form-group row">
        <label class="col-md-3 col-form-label">Name</label>
        <div class="col-md-9">
            <input type="text" autocomplete="off" asp-for="Name" name="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">Phone</label>
        <div class="col-md-9">
            <input type="number" autocomplete="off" asp-for="PhoneNumber" name="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-md-3 col-form-label">Email</label>
        <div class="col-md-9">
            <input type="email" autocomplete="off" asp-for="Email" name="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-3">
        </div>
    </div>
    <div class="form-group justify-content-between">
        <button type="button" class="btn btn-secondary close-button" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary save-button">Save</button>
    </div>
</form>
<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

ContactListManagement.Web/Pages/_ViewAll.cshtml
@using Core.Entities
@model IEnumerable<ContactList>
<table class="table table-bordered" id="contactListTable">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                PhoneNumber
            </th>
            <th>
                Email
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() != 0)
        {
            @foreach (var contactList in Model)
            {
                <tr>
                    <td>
                        @contactList.Name
                    </td>
                    <td>
                        @contactList.PhoneNumber
                    </td>
                    <td>
                        @contactList.Email
                    </td>
                    <td text-right">
                        <a onclick="jQueryModalGet('?handler=CreateOrEdit&id=@contactList.Id','Edit Contact List')" class="btn btn-info text-white"> Edit</a>
                        <form method="post" asp-page="Index" asp-route-id="@contactList.Id" asp-page-handler="Delete" onsubmit="return jQueryModalDelete(this)" class="d-inline">
                            <button type="submit" class="btn btn-danger text-white"> Delete</button>
                        </form>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
<script>
    $(document).ready(function () {
        $("#contactListTable").DataTable();
    });
</script>